Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2018-08, with the labels that each got.

#560 Fix formatting of backticks on icache.doc
  src/docs/asciidoc/jcache/icache.adoc
Labels: Cosmetic

#564 Added documentation related to latest WAN related additions:
  src/docs/asciidoc/dds.adoc
  src/docs/asciidoc/wan.adoc
  src/main/java/distributedevents/Listen.java
Labels: Add to Release Notes, Content Enhancement

#557 Provide documentation on index statistics
  src/docs/asciidoc/management.adoc
  src/main/java/management/SampleLocalIndexStats.java
Labels: Content Enhancement

#567 Update section about TLS
  src/docs/asciidoc/security.adoc
Labels: Content Enhancement

#571 Adds JCache eager expiry
  src/docs/asciidoc/jcache/api.adoc
Labels: Content Enhancement

#570 Adds a line about IMap.setTTL in evicting specific entries section
  src/docs/asciidoc/dds.adoc
Labels: Content Enhancement
