Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2018-12, with the labels that each got.

#616 Add Toggle scripting under Management Center section
  src/docs/asciidoc/management.adoc
Labels: Content Enhancement

#615 Add Toggle scripting under Management Center section
  src/docs/asciidoc/management.adoc
Labels: Content Enhancement

#622 Remove obsolete MC param
  src/docs/asciidoc/system_properties.adoc
Labels: Content Enhancement

#623 Fix OpenSSL Maven dependency snippet
  src/docs/asciidoc/security.adoc
Labels: Bug

#624 [BACKPORT 3.11.z] Fix OpenSSL Maven dependency snippet
  src/docs/asciidoc/security.adoc
Labels: Bug

#621 Added section for dynamically adding WAN configuration
  src/docs/asciidoc/wan.adoc
Labels: Missing Content
