Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2019-12, with the labels that each got.

#786 Make WAN javadoc links to point to latest
  src/docs/asciidoc/wan.adoc
Labels: Cosmetic

#785 Add metrics documentation
  src/docs/asciidoc/management.adoc
  src/docs/asciidoc/migration_guides.adoc
  src/docs/asciidoc/system_properties.adoc
Labels: Content Enhancement

#790 Add validateIdentity option to TLS sections. Remove invalid note abou…
  src/docs/asciidoc/security.adoc
Labels: Content Enhancement

#792 Document bitmap indexes
  src/docs/asciidoc/distributed_query.adoc
Labels: Priority: High

#788 Describe changes in Management Center configuration and REST API
  src/docs/asciidoc/management.adoc
  src/docs/asciidoc/migration_guides.adoc
  src/docs/asciidoc/preface.adoc
  src/docs/asciidoc/security.adoc
  src/docs/asciidoc/system_properties.adoc
  src/docs/asciidoc/understanding_configuration.adoc
  src/docs/asciidoc/wan.adoc
Labels: Content Enhancement
