Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2019-03, with the labels that each got.

#661 Add note for CP member shutdown
  src/docs/asciidoc/cp_subsystem.adoc
Labels: Content Enhancement

#663 Add CP Subsystem Discovery section
  src/docs/asciidoc/cp_subsystem.adoc
Labels: Missing Content

#665 Update CP Subsystem docs
  src/docs/asciidoc/cp_subsystem.adoc
Labels: Content Enhancement

#666 Fix curl of health ready check
  src/docs/asciidoc/management.adoc
Labels: Bug

#667 Mention the CP Subsystem discovery API
  src/docs/asciidoc/cp_subsystem.adoc
Labels: Content Enhancement, Missing Content

#671 Rename exception
  src/docs/asciidoc/cp_subsystem.adoc
Labels: Content Enhancement

#672 Cleanup sample code
  src/docs/asciidoc/performance.adoc
  src/main/java/performance/OrderKey.java
Labels: Content Enhancement
