Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2019-02, with the labels that each got.

#638 Update Hot Restart base-dir section for shared usage
  src/docs/asciidoc/storage.adoc
Labels: Add to Release Notes, Content Enhancement

#640 Remove obsolete MC parameter
  src/docs/asciidoc/system_properties.adoc
Labels: Content Enhancement

#641 [BACKPORT] Remove obsolete MC param
  src/docs/asciidoc/system_properties.adoc
Labels: Content Enhancement

#644 Change client attributes with client labels
  src/docs/asciidoc/hazelcast_clients.adoc
  src/docs/asciidoc/revision_history.adoc
Labels: Content Enhancement

#646 Document cluster version auto upgrade
  src/docs/asciidoc/rolling_member_upgrades.adoc
Labels: Content Enhancement

#639 Add section for CP Subsystem
  src/docs/asciidoc/consistency.adoc
  src/docs/asciidoc/cp_subsystem.adoc
  src/docs/asciidoc/dds.adoc
  src/docs/asciidoc/images/FencedLock.png
  src/docs/asciidoc/index.adoc
  src/main/java/cp/CpSubsystemAPI.java
  src/main/java/cp/CpSubsystemConfiguration.java
  src/main/java/dds/ExampleIAtomicReference.java
  src/main/java/dds/countdownlatch/Follower.java
  src/main/java/dds/countdownlatch/Leader.java
  src/main/java/dds/iatomiclong/ExampleIAtomicLong.java
  src/main/java/dds/iatomiclong/IAtomicLongExecuteFuncs.java
  src/main/java/dds/lock/ExampleLock.java
  src/main/java/dds/lock/LockConfiguration.java
  src/main/java/dds/semaphore/SemaphoreMember.java
Labels: Add to Release Notes, Content Enhancement

#650 Add a Security subsection about FIPS 140-2 configuration
  src/docs/asciidoc/security.adoc
Labels: Content Enhancement

#653 Json querying
  src/docs/asciidoc/dds.adoc
  src/docs/asciidoc/distributed_query.adoc
Labels: Content Enhancement

#654 Advanced network configuration documentation
  src/docs/asciidoc/setting_up_clusters.adoc
  src/main/java/settingupclusters/AdvancedNetworkConfig.java
Labels: Content Enhancement

#655 Updates JVM compatibility table (min Java 8 requirement since 3.12)
  src/docs/asciidoc/distributed_query.adoc
  src/docs/asciidoc/getting_started.adoc
  src/docs/asciidoc/security.adoc
Labels: Content Enhancement

#657 Added section on WAN latency and throughput tuning
  src/docs/asciidoc/wan.adoc
Labels: Missing Content

#658 Document YAML configuration
  src/docs/asciidoc/understanding_configuration.adoc
Labels: Content Enhancement

#659 Added pipelining documentation
  src/docs/asciidoc/performance.adoc
Labels: Content Enhancement
