Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2019-10, with the labels that each got.

#697 Update MigrationListener section due to API change
  src/docs/asciidoc/distributed_events.adoc
  src/main/java/distributedevents/ClusterMigrationListener.java
Labels: Add to Release Notes, Content Enhancement

#723 Add documentation for CP Subsystem Persistence
  src/docs/asciidoc/cp_subsystem.adoc
  src/main/java/cp/CPSubsystemPersistence.java
Labels: Content Enhancement, Missing Content

#729 Use Hazelcast dynamic version in JCache documentation
  src/docs/asciidoc/getting_started.adoc
  src/docs/asciidoc/getting_started_HAZELCAST-MEMBER-TOOL.adoc
  src/docs/asciidoc/hazelcast_clients.adoc
  src/docs/asciidoc/integrated_clustering.adoc
  src/docs/asciidoc/jcache/setup.adoc
  src/docs/asciidoc/understanding_configuration.adoc
Labels: Content Enhancement

#727 Remove deprecated LocalReplicatedMapStats.getReplicationEventCount
  src/docs/asciidoc/management.adoc
Labels: Content Enhancement

#740 Predicate API cleanup: updated the manual
  src/docs/asciidoc/dds.adoc
  src/docs/asciidoc/distributed_query.adoc
  src/docs/asciidoc/system_properties.adoc
  src/main/java/dds/map/ListenerWithPredicate.java
Labels: Content Enhancement

#738 Javadoc JAR for EE: added an example
  src/docs/asciidoc/getting_started.adoc
Labels: Content Enhancement

#737 fixed a typo
  src/docs/asciidoc/migration_guides.adoc
Labels: Cosmetic

#744 Improve section on lambda-friendly-interfaces
  src/docs/asciidoc/migration_guides.adoc
Labels: Content Enhancement

#746 fixed a typo
  src/docs/asciidoc/migration_guides.adoc
Labels: Cosmetic

#747 Added documentation for Hot Restart Encryption at Rest
  src/docs/asciidoc/storage.adoc
  src/main/java/storage/SampleEncryptionAtRestConfiguration.java
Labels: Missing Content

#748 Added documentation for Hot Restart Encryption at Rest
  src/docs/asciidoc/storage.adoc
  src/main/java/storage/SampleEncryptionAtRestConfiguration.java
Labels: Missing Content

#735 Rename CPSubsystemManagementService.restart() to .reset()
  src/docs/asciidoc/cp_subsystem.adoc
  src/main/java/cp/CpSubsystemAPI.java
Labels: Content Enhancement

#749 Add 4.0 migration guide for legacy concurrency api
  src/docs/asciidoc/migration_guides.adoc
Labels: Content Enhancement

#733 Add documentation for initial permit count of Semaphore
  src/docs/asciidoc/cp_subsystem.adoc
  src/main/java/cp/CpSubsystemConfiguration.java
Labels: Missing Content

#750 Updated entry processor sections for 4.0
  src/docs/asciidoc/distributed_computing.adoc
  src/docs/asciidoc/system_properties.adoc
  src/main/java/distributedcomputing/IncrementingEntryProcessor.java
Labels: Content Enhancement

#751 Updated section for custom query attributes
  src/docs/asciidoc/distributed_query.adoc
  src/docs/asciidoc/migration_guides.adoc
Labels: Content Enhancement

#752 Update security in migration guide 4.0-Beta1
  src/docs/asciidoc/getting_started.adoc
  src/docs/asciidoc/migration_guides.adoc
Labels: Content Enhancement

#753 Document removal of legacy merge policies
  src/docs/asciidoc/integrated_clustering.adoc
  src/docs/asciidoc/migration_guides.adoc
  src/docs/asciidoc/wan.adoc
  src/main/java/wan/EnablingWRforCache.java
Labels: Add to Release Notes, Content Enhancement

#754 Update migration sections for WAN replication changes
  src/docs/asciidoc/migration_guides.adoc
Labels: Content Enhancement

#755 Cover security config migration
  src/docs/asciidoc/migration_guides.adoc
  src/main/java/cp/CpSubsystemAPI.java
  src/main/java/cp/CpSubsystemConfiguration.java
Labels: Content Enhancement

#756 Update WAN replication section for 4.0 changes
  src/docs/asciidoc/wan.adoc
  src/main/java/wan/ExampleWANReplicationConfiguration.java
  src/main/java/wan/ExampleWANReplicationDiscoveryConfiguration.java
Labels: Content Enhancement

#765 Hazelcast 4.0 security changes
  build.gradle
  src/docs/asciidoc/hazelcast_clients.adoc
  src/docs/asciidoc/security.adoc
  src/docs/asciidoc/setting_up_clusters.adoc
  src/docs/asciidoc/understanding_configuration.adoc
  src/main/java/security/ldap/CustomSSLSocketFactory.java
  src/test/java/security/CustomLoginModuleTest.java
  src/test/java/security/SecurityXmlTest.java
  src/test/resources/hazelcast-authentication-types.xml
  src/test/resources/hazelcast-password-realm.xml
  src/test/resources/hazelcast-security-realms.xml
Labels: Content Enhancement

#766 Property hazelcast.client.protocol.max.message.bytes added
  src/docs/asciidoc/system_properties.adoc
Labels: Content Enhancement

#767 Hazelcast Security logging
  src/docs/asciidoc/security.adoc
Labels: Content Enhancement
