Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2020-08, with the labels that each got.

#840 Rewrite/Rearrangement of the Getting Started and Overview chapters.
  src/docs/asciidoc/docinfo-footer.html
  src/docs/asciidoc/getting_started.adoc
  src/docs/asciidoc/hazelcast_overview.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/installing_upgrading.adoc
  src/docs/asciidoc/rolling_member_upgrades.adoc
  src/docs/asciidoc/starting_members_clients.adoc
Labels: Content Enhancement, Missing Content

#860 Adds documentation for instance tracking
  src/docs/asciidoc/management.adoc
  src/docs/asciidoc/management/cluster_utilities.adoc
  src/docs/asciidoc/management/diagnostics.adoc
  src/docs/asciidoc/management/health_check_monitoring.adoc
  src/docs/asciidoc/management/instance_tracking.adoc
  src/docs/asciidoc/management/jmx_api.adoc
  src/docs/asciidoc/management/jmx_monitoring.adoc
  src/docs/asciidoc/management/management_center.adoc
  src/docs/asciidoc/management/member_statistics.adoc
  src/docs/asciidoc/management/metrics.adoc
  src/docs/asciidoc/management/rest_endpoint_groups.adoc
Labels: Missing Content

#844 Add documentation for CP Subsystem listeners
  src/docs/asciidoc/cp_subsystem.adoc
  src/main/java/cp/event/CPGroupAvailabilityListenerImpl.java
  src/main/java/cp/event/CPMembershipListenerImpl.java
Labels: Add to Release Notes, Content Enhancement
