Repository hazelcast/hazelcast-reference-manual, pull requests merged in 2020-11, with the labels that each got.

#891 Small update to priority queue documentation
  src/docs/asciidoc/dds.adoc
Labels: Content Enhancement, Cosmetic

#892 Small update to priority queue documentation
  src/docs/asciidoc/dds.adoc
Labels: Content Enhancement, Cosmetic

#897 Update rolling upgrade versions
  src/docs/asciidoc/installing_upgrading.adoc
Labels: Content Enhancement

#898 Fix a bug in 'configuration override section'
  src/docs/asciidoc/understanding_configuration.adoc
Labels: Bug
